### ISSUE TITLE
Configuration for proper clearing

### ISSUE THREAD

**Issue by neomanic** [SteveMacenski/spatio_temporal_voxel_layer#111] opened 2019-02-20 05:03 UTC
Hi Steve,

I've just started using this layer, and the speed compared to the old voxel grid is amazing.

I am having trouble with configuration though, I can't seem to get the frustum clearing working. We have two depth cameras mounted to give a wide angle of view, and at about 1.2m above the ground pointing down to use for collision avoidance. We do want the decay so objects that we've moved past disappear eventually, but not too quickly such that we can decide to turn in to them. I'd like it to be more than 3 seconds as per the config below.

The problem seems to be that previous observations just stay in the voxel map, ie; the clearing doesn't seem to be happening at all. For example, if a person walks across the view of the cameras, there's a "trail" that follows behind them and blocks the path.

Is there anything immediately obvious I'm doing wrong? I wasn't quite sure how the frustum spec works, particularly as the cameras are mounted vertically (so they have a narrower FOV horizontally than vertically), and they are pointed at an angle to the ground.

Note that I've included the lidar below, but I have run it fine in a separate layer, it's just the depth cameras I'm concerned with.

Relevant section of the layer config:
```
    spatio_temporal_voxel_layer:
        enabled:                  true
        voxel_decay:              3     #seconds if linear, e^n if exponential
        decay_model:              0      #0=linear, 1=exponential, -1=persistent
        voxel_size:               0.025   #meters
        track_unknown_space:      true   #default space is unknown
        observation_persistence:  0.0    #seconds
        max_obstacle_height:      1.2    #meters
        unknown_threshold:        15     #voxel height
        mark_threshold:           0      #voxel height
        update_footprint_enabled: true
        combination_method:       1      #1=max, 0=override
        obstacle_range:           3.0    #meters
        origin_z:                 0.0    #meters
        publish_voxel_map:        true   # default off
        transform_tolerance:      0.2    # seconds
        mapping_mode:             false  # default off, saves map not for navigation
        map_save_duration:        60     #default 60s, how often to autosave
        observation_sources:      depth_left_marking depth_left_clearing depth_right_marking depth_right_clearing lidar 
        
        lidar:
            data_type: LaserScan
            topic: /scan
            inf_is_valid: true
            expected_update_rate: 0.2
            marking: true
            clearing: true
            decay_acceleration: 0
            
        depth_left_marking:
            data_type: PointCloud2
            topic: /rs_left/depth/points_filtered
            marking: true
            clearing: false
            min_obstacle_height: 0.03     #default 0, meters
            max_obstacle_height: 1.0     #default 3, meters
            expected_update_rate: 0.0    #default 0, if not updating at this rate at least, remove from buffer
            observation_persistence: 0.0 #default 0, use all measurements taken during now-value, 0=latest 
            inf_is_valid: false          #default false, for laser scans
            clear_after_reading: true    #default false, clear the buffer after the layer gets readings from it
            voxel_filter: true           #default off, apply voxel filter to sensor, recommend on 
        depth_left_clearing:
            data_type: PointCloud2
            topic: /rs_left/depth/points_filtered
            marking: false
            clearing: true
            min_z: 0.1                   #default 0, meters
            max_z: 2.0                   #default 10, meters
            vertical_fov_angle: 1.48      #default 0.7, radians, 85.2° = 1.48
            horizontal_fov_angle: 1.01   #default 1.04, radians, 58° = 1.01
            decay_acceleration: 1.       #default 0, 1/s^2. If laser scanner MUST be 0

(...depth_right is identical to depth_left...)
```

**Comment by SteveMacenski** [comment] 2019-02-20 05:13
I would recommend removing the lidar from this layer and using the obstacle layer for that - it works better for the 2D lidar case.

Your config file doesn't tell me the update rate on your layer to jot down some calculations, but I'm going to guess `decay_acceleration` is too low at 1. Think about this value as the alpha acceleration in the traditional kinematics model. Try 5 or 15 and see if that helps.

additional questions of its not just a `decay_acceleration` issue:
What's the relative distance between the sensor frame and the object(s) that's not clearing? 
I see the vertical FOV is larger than the horizontal FOV, that seems suspect. Generally depth cameras are wider than taller - especially that I notice your values are the same as the realsense D435s (:wink: ) so I know that's probably switched

**Comment by neomanic** [comment] 2019-02-20 06:32
Thanks.

Lidar: I’ll move it back to the obstacle later.

Update rate: we are running at 6Hz. We’re moving very slowly (0.3 m/s max) so didn’t think that to be an issue. The distance to the obstacle could be anything. 

You’re right, they are 435s. But there are two, mounted vertically... is the frustum in the depth camera tf frame, such that I should switch the values back around? Was going to dig through the source but thought it much quicker to ask.  I’m running them through my own PCL-based filtering and decimation first, and doing my own transform into base-link... is that an issue?

**Comment by SteveMacenski** [comment] 2019-02-20 06:45
The FOVs are respective to the frame the information is coming in under. 

acceleration fix your issue?

**Comment by neomanic** [comment] 2019-02-21 00:16
Sorry for slow reply... I'm over the other side of the planet and had to sleep. ;) I've removed the lidar back to a stock obstacle layer (although it's not as good at clearing as yours), removed my point cloud preprocessing and just let the STVL handle the voxel filtering, fixed the frustrum, and tweaked acceleration up to 15 (not that I quite understand it still).

[Top down view](https://youtu.be/0YD_gbvA2F0): I walk across and back about 1m in front of the cameras.
[Side view](https://youtu.be/-2nZ1kJeI8w): Walked across, walked back faster, then ran across

I *think* it's better, but there's still some residual artifacts that don't seem to clear very quickly. See the first time I walk across in the perspective video: my legs below the knee take a while to clear. It seems to clear quicker when there isn't an obstacle close behind me?

**Comment by SteveMacenski** [comment] 2019-02-21 00:53
The colors are a little distracting to debug, but since your voxel decay is 3 seconds, I dont think that's actually acceleration  but the global voxel_decay doing that. 

I see your max_z for clearing is 2m, but your obstacle range is 3m, that means there's a whole 1m in the back of the frustum not being cleared out at all but still able to mark. I'd take a good hard look at the parameters and what they mean and revisit your configuration - it looks like you have a number of configuration issues and its hard for me to pick them all out. 

Get the source code and visualize the frustums setting this to `1` https://github.com/SteveMacenski/spatio_temporal_voxel_layer/blob/kinetic-devel/include/spatio_temporal_voxel_layer/frustum_models/depth_camera_frustum.hpp#L50 and checking in rviz for the appropriate markers. Try one camera at a time. See that the frustum is correctly attached and your frames make sense. Its possible you have issues in your TF tree. 

Ps setting that to 1 will destroy performance, its a debug tool. Expect 1hz update or worse while figuring out those issues.

PPs, that's an interesting looking robot

**Comment by neomanic** [comment] 2019-02-21 01:01
Thanks Steve, really appreciate the help. I'll try what you've suggested. 

That max_z at 2.0 thing was really dumb of me, I must have assumed it was the height of obstacles. I'll read over it all more carefully and try what you've suggested.

**Comment by SteveMacenski** [comment] 2019-02-21 01:11
No worries, this isn't a trivial thing to set up.

**Comment by neomanic** [comment] 2019-02-21 03:25
That did the trick,
![frustum_original](https://user-images.githubusercontent.com/3894923/53137421-d7b8d980-35d6-11e9-99bc-9ade99b230a6.jpg)
![frustum_fixed](https://user-images.githubusercontent.com/3894923/53137424-d8517000-35d6-11e9-887d-357d037f0bf4.jpg)

Still tweaking, but it's looking much better.

**Comment by SteveMacenski** [comment] 2019-02-21 04:18
Looks like you've probably found your issues. 

Side note: I'm writing a paper right now on this project and its impact on/from the open source community, if you're open to sharing more about your application (privately and anonymously made statistics of) please feel free to email me at stevenmacenski@gmail.com. Right now I have confirmed robots in warehouse, retail, hospitals, research labs, and looks like you have something interesting here as well

**Comment by nickvaras** [comment] 2019-02-21 13:59
add factories.

**Comment by SteveMacenski** [comment] 2019-02-21 22:00
Looks like the email got cut out - you can see it in the package.xml as well

**Comment by SteveMacenski** [comment] 2019-02-25 18:51
Any updates or all is working now?

**Comment by nickvaras** [comment] 2019-02-25 21:54
You can add "Factories" to the list (warehouse, retail, hospitals, research labs)

**Comment by SteveMacenski** [comment] 2019-02-26 00:19
Added a reame to the effect (I'm not sure I had a publicly available list)

**Comment by neomanic** [comment] 2019-02-26 12:16
Sorry, am on-site and demoing the robot this week. Is working really well though, no complaints at all. I trialled the global + permanent option today so we can generate a static 'preferred route' costmap, and the output voxel grid is valuable to that end.

![screenshot 2019-02-26 23 50 39](https://user-images.githubusercontent.com/3894923/53412102-8cf6f180-3a1c-11e9-9f76-469036ed2964.jpg)

**Comment by SteveMacenski** [comment] 2019-02-26 20:42
Great! Do you mind then if we close this ticket as resolved?

**Closed** 2019-02-26 21:10 UTC
